### ISSUE TITLE
since 1.17.0 (touch) scroll is buggy

### ISSUE THREAD

**Issue by younes0** [maxmarinich/react-alice-carousel#102]
on 1.17.0, touch scroll doesn't display fully the next item:
you have to scroll a much longer distance to see next item: 
![image](https://user-images.githubusercontent.com/886042/71267810-c69e3d80-234b-11ea-81ad-ba78a3725f08.png)

You can check it out on: https://feature-spa-65olxfa-l7v65o3lxb7ty.eu-3.magentosite.cloud/fr_fr/robe-longue-soie-imprime-camelia-rose-rouge.html
And the 1.16.0 behavior on: https://www.thekooples.com/fr_fr/manteau-fausse-fourrure-noir-court-ffou19046kbla01.html

Could this commit be the issue ?
https://github.com/maxmarinich/react-alice-carousel/commit/417d1f5006e7e61854f0f4670b5b10c705cddfc4

Thanks.

**Comment by maxmarinich** [comment]
Hi, @younes0! Live [demo](https://zrlmr3p61m.csb.app/). It works like expected. Possible, the problem is not for Gallery. In my case, I set  `li.alice-carousel__stage-item -> img = width: 100%` (For any reason, some images have `width: 1px`).  And the problem has been resolved.

**Comment by younes0** [comment]
thanks @maxmarinich 
images with 1px are placeholders: the real images are lazy loaded, and placeholders are removed.
The problem still exists if all images are loaded (scroll all images one time for that) or if all images (even placeholders) have a 100% width.

**Comment by younes0** [comment]
Thanks @maxmarinich, I have updated the lib to 1.17.1 
There are still the same issues.

**Comment by maxmarinich** [comment]
@younes0, to avoid side effects, could you create a simple sample on [sandbox](https://codesandbox.io/s/zrlmr3p61m)? And try get the same there. Looks weird, I can't reproduce it with your previous example.

**Comment by younes0** [comment]
Will do! Thanks

**Comment by michaelmika** [comment]
We also have buggy problems on mobile still in version 1.17.3. We have child elements with 100% width.

**Comment by younes0** [comment]
Sorry my lack of response. I didn't need all of the features that provides this great library so I've switched to https://github.com/davidcetinkaya/embla-carousel-react

**Comment by maxmarinich** [comment]
Fixed in #116
